fix/UI Issue fixed
danger-ahead/flutter_dictionary pull request #34
Opened 2023-10-12 21:29 UTC by ayato91

Addition of physics can help to retrieve those covered words.

2023-10-13 21:27 UTC, ayato91 commented
@danger-ahead can you please check and share your review?

2023-10-15 09:51 UTC, danger-ahead commented
Can you share a demo of the fix? Maybe a screenshot or recording?

2023-10-15 15:10 UTC, ayato91 commented
Sure, I will share those as well

2023-10-15 18:02 UTC, ayato91 commented
Preview added!
<img width="250" height="500" src="https://github.com/ayato91/flutter_dictionary/blob/1ddafc3388f286d6701623b5769b5de4a1cdfed1/images/Scroll_effect.gif" alt="Scrolling Effect Animation" />

2023-10-15 19:24 UTC, danger-ahead commented
> @danger-ahead Preview added! <img alt="Scrolling Effect Animation" height="500" src="images/Scroll_effect.gif"> [ <img alt="Scrolling Effect Animation" height="500" src="https://github.com/danger-ahead/flutter_dictionary/pull/images/Scroll_effect.gif"> ](https://github.com/danger-ahead/flutter_dictionary/pull/images/Scroll_effect.gif) [ ](https://github.com/danger-ahead/flutter_dictionary/pull/images/Scroll_effect.gif)

Hey, Sorry for the confusion. I just wanted to see a demo. You don't need to add the file. Delete it, I have gone through the demo. And then, we'll be ready to merge.

2023-10-15 19:25 UTC, danger-ahead requested changes
just 1 change, rest LGTM!

2023-10-15 19:25 UTC, danger-ahead commented on images/Scroll_effect.gif
Need to remove this.

2023-10-15 19:58 UTC, danger-ahead approved these changes

2023-10-15 19:58 UTC, merged